### ISSUE TITLE
Prevent Exim from adding Sender header

### ISSUE THREAD

**Issue by freakynl** [akissa/baruwa2#158]
Currently Exim adds a Sender header to e-mails where the mail (smtp/envelope) from and (header) from differ.

Many companies are starting to use [BATV](https://en.wikipedia.org/wiki/Bounce_Address_Tag_Validation). Several e-mail clients, among which Outlook, show <sender> on behalf of <header from>, if this is set.

So they're looking at a lot of ugly inbox message that look something along the lines of:

prvs=SOME-UGLY-LONG-ID-132415182=JohnDoe@domain.tld on behalf of John Doe <JohnDoe@domain.tld>.

Haven't found a way to disable this. It's also a bit redundant as there's a feature in the message processing called 'Add Envelope From Header'. This sets a X-%org%-BaruwaFW-Envelope-From which basically does the same, but doesn't have this unfortunate side effect.

**Comment by tomtakan** [comment]
This is not the default behavior, that is only added if the admin turns on the `Add Sender Header` option in baruwa-setup
https://docs.baruwa.com/configuration/backend.html#mta-more-settings
