### ISSUE TITLE
[Feature Request] LDAP profiles to automatically update/sync aliases

### ISSUE THREAD

**Issue by ajendoubi** [akissa/baruwa2#28]
Hi,
At the moment the LDAP configuration works well and pull all the details (aliases) once a new user login to baruwa the first time, however as we all know, some aliases for a user might be added after few days/months, as well as they might be modified or even deleted, in the current Baruwa status the domain admin have two options:
1) manually update/modify/delete the user aliases - this can be very frustrating to manually update each account in >30 profiles
2) delete the user profile from baruwa and then ask the user to re-login - this is uncomfortable for users that don't login often to the baruwa portal and just use the quarantine report to release false positives.

So, by giving an automation to the profiles imported through LDAP (it can be a script ran 1-ce a day by a cronjob to pull/update the users details), it would make life easier and Baruwa having a 100% effective tool/functionality.

I hope this will be accepted and implemented soon :)
Cheers,
Anis

**Comment by akissa** [comment]
Fixed in dad10eb36ad27c1115380159a765ee6b93518400
