### ISSUE TITLE
[Feature request] - outbound general rules per organisation

### ISSUE THREAD

**Issue by ajendoubi** [akissa/baruwa2#33]
Some of baruwa admins would like to customise the outbound filtering rules to tweak them according to their company internal rules (f.e. raising the score level of probable spams or definite spams, deliver the probable spams or just quarantine them, etc etc...)
it could be useful to have such functionality in the interface to customise outbound rules per organisation.
Cheers,
A.J.

**Comment by akissa** [comment]
Fixed in dad10eb36ad27c1115380159a765ee6b93518400
