### ISSUE TITLE
Alias Domain adding to user account - The domain: xxxxxxxxxxxxxxxx.com is not local

### ISSUE THREAD

**Issue by TetraAsh** [akissa/baruwa2#51]
We have a domain setup domain.co.uk and we added an alias of domain.com.

Then we added a user account on that domain user@domain.co.uk and tried to add a alias address to that user user@domain.com but when we try to add this we get an error "The domain: domain.com is not local"
As a note: Installation was done with www.baruwa-install.com, it could be related but doubting it.

My Poor solution so far

https://github.com/akissa/baruwa2/blob/master/baruwa/forms/accounts.py

class AddressForm(Form):
"""Add alias address"""
address = TextField(_('Email Address'),
[validators.Required(message=REQ_MSG),
validators.Email(message=EMAIL_MSG), check_domain])
enabled = BooleanField(_('Enabled'))

Can be edited to

class AddressForm(Form):
"""Add alias address"""
address = TextField(_('Email Address'),
[validators.Required(message=REQ_MSG),
validators.Email(message=EMAIL_MSG)])
enabled = BooleanField(_('Enabled'))

This removes the CHECK_DOMAIN validation and rely on user competence (dangerous i know) but works.

**Comment by akissa** [comment]
Fixed in dad10eb36ad27c1115380159a765ee6b93518400
