### ISSUE TITLE
Is baruwa2 still under development?

### ISSUE THREAD

**Issue by topstarnetwork** [akissa/baruwa2#57]
Is baruwa2 still under development?
As I see that the enterprise Baruwa 2.0.6 Enterprise Edition has multiple update releases,
thanks.

**Comment by akissa** [comment]
Yes we will backport the changes from enterprise soon, your contributions are welcome as well.

**Comment by topstarnetwork** [comment]
As I am not a coder I really can't help.
Woul dyou have any estimated date for when will the backport  changes from enterprise be?
Regards, Heather

**Comment by akissa** [comment]
I do not have an ETA as busy with features in enterprise right now, only when done and have free time on my hands will i begin the backports but looking at possibly mid this year, we could just rebase the community version on the current enterprise but time will tell.

**Comment by topstarnetwork** [comment]
Would you have any newsletter to which I could subscribe in order to stay tuned?
Regards, Heather

**Comment by akissa** [comment]
You can subscribe to our community mailing list - https://www.baruwa.org/community/

**Comment by pndiku** [comment]
Hi Andrew,

Any updates for us? If you need help I'm willing to contribute the time to test and bug-fix. (Although I'd love it if you just rebased!)

**Comment by akissa** [comment]
Will need more than testing, if someone can do the documentation as well. I should be able to get some time to push back to community but will just push the source, the community will need to test and document.

**Comment by extremeshok** [comment]
What license is baruwa free under ?

**Comment by pndiku** [comment]
I'm offering to write documentation for Centos & SUSE

**Comment by akissa** [comment]
Great will would on the rebase

**Comment by akissa** [comment]
@extremeshok it is GPLv3

**Comment by akissa** [comment]
2.0.9 enterprise rebased dad10eb36ad27c1115380159a765ee6b93518400 into community, you can now work on testing and documenting that
