### ISSUE TITLE
question: build servers

### ISSUE THREAD

**Issue by extremeshok** [akissa/baruwa2#60]
Hi Andrew, curious to know what your using as your build service/platform for rpm and debs.

**Comment by akissa** [comment]
Everything is built manually using rpmbuild, not using a service

**Comment by extremeshok** [comment]
for .deb as well ?

**Comment by akissa** [comment]
Used to use pbuilder for deb's we no longer support debs.

**Comment by extremeshok** [comment]
thanks ;_)
