### ISSUE TITLE
Allow CIDRs in exemption lists

### ISSUE THREAD

**Issue by petergreen** [akissa/baruwa2#61]
We would like to be able to use CIDRs as keys for some of the databases (e.g., /var/lib/baruwa/data/db/allow_empty_replyto.cdb) that run the exemption lists. At present, exim.conf uses a straight cdb lookup against that database:

          condition     = ${lookup{$sender_host_address}cdb{/var/lib/baruwa/data/db/allow_empty_replyto.cdb}{0}{1}}

Instead, could it be adjusted to use the Perl-based "ip_in_network" call?

          condition     = ${perl{ip_in_network}{/var/lib/baruwa/data/db/bannedlists.cdb}{$sender_host_address}}

Is it possible to incorporate that into the main configuration and UI?

**Comment by akissa** [comment]
Implemented, testing to be released soon as an update or as part of 2.0.10

**Comment by bpikkaart** [comment]
Thanks!
