### ISSUE TITLE
cython & archive-download.py'  also directory structure on 2.0.9

### ISSUE THREAD

**Issue by watrob** [akissa/baruwa2#62]
Hi,
I have over come the install error with pip install baruwa (2.0.9), in the setup.py file which has "archive-download.py" and "from Cython.Build import cythonize" lines, I have removed them from the setup.py file of baruwa-2.0.9.

I downloaded the tar.gz file and removed the two lines but because I am then installing under "python setup.py install" it does not make the directory "home/baruwa/px/lib/python2.6/site-packages/baruwa", only the baruwa-2.0.9-py2.6.egg directory (pip install baruwa-2.0.1 did create the baruwa directory) so now when I go to patch the baruwa directory it is not found due to it not being created.
 I have checked the build process between 2.0.1 & 2.0.9 and found that 2.0.9 uses a different directory structure, it places the baruwa directory in the "baruwa-2.0.9-py2.6.egg" directory ( it does for me anyway).........is this correct?

I am in the process of changing my script tonight so the patches will apply to the new directory structure.
 I also I do not know why the setup.py file has these two line when site says they are removed? from setup.py, not sure if this is a left over requirement from the Enterprise Edition of 2.0.9? it would make the install via pip a lot easier if they where removed?

I don't know why the "baruwa" directory is inside the "baruwa-2.0.9-py2.6.egg" directory, not sure if its a build problem but I don't see any build errors, or if its because I am using "python setup.py install" and not "pip install". It would be good if we could get some direction on this? to find out if this is correct or is there a build directory error in baruwa-2.0.9?. Baruwa-2.0.1 builds ok with a separate baruwa directory outside of  "egg"

The "python setup.py install" runs thru to the end and I can make a "production.ini" file, its just now I have the "baruwa" directory inside of the "baruwa-2.0.9-py2.6.egg" directory?
Thanks

**Comment by akissa** [comment]
Use the git version not the PyPi version
