### ISSUE TITLE
Wrong link to EDIT SA score rule

### ISSUE THREAD

**Issue by syska** [akissa/baruwa2#64]
When viewing a message and clicking the SA rule which has been hit. The link looks like this:

https://foo.bar.tld/settings/scores/edit/KAM_LAZY_DOMAIN_SECURITY

Which is wrong, cause when browsing to this page, it looks like an INTEGER ... like f.eks:

https://foo.bar.tld/settings/scores/edit/1432

**Comment by akissa** [comment]
Fixed, will be released in the next update
